import type { DashboardState } from "./types";

export const dashboardSeed: DashboardState = {
  version: 3,
  profile: {
    title: "Fries",
    currentMode: "OpenAI 主线账号运营盘 + 其他 provider 观察盘",
    summary:
      "当前默认先用 Codex / GPT 流量池；Claude、Kimi 降级为观察或兜底，Gemini 仅保留静态观察，GLM-OCR 保留精确额度监控。",
    strategyNotes: [
      "OpenAI Team / Business 坑位视作可扩展的订阅型流量包。",
      "Claude 暂不做默认执行器，但保留回归主线的观察位。",
      "Kimi 当前主要是保留历史配置，不再承担日常主力。",
      "Gemini 低频保留，当前不接实时抓取，只保留静态观察位。",
    ],
    lastReviewedAt: "2026-03-16",
  },
  settings: {
    syncIntervalMinutes: 1,
    snapshotRetentionDays: 14,
    autoSyncOnLaunch: true,
    themeMode: "system",
    themePreset: "nordic-blue",
    locale: "zh-CN",
    visualEffectMode: "frosted",
    performanceMode: false,
    timelineScope: "week",
    analyticsRange: "week",
    analyticsChartMode: "line",
    heatmapScope: "month",
  },
  accounts: [
    {
      id: "openai-primary-a",
      provider: "OpenAI",
      accountLabel: "RobertGreene7794",
      email: "sunriseforever747@outlook.com",
      plan: "ChatGPT Team",
      cluster: "openai",
      status: "active",
      priority: 1,
      isActive: true,
      workspace: "RobertGreene7794",
      statusDetail: "当前有可用流量，作为微软主号下的主力 Team 继续顶住日常 Codex / GPT 工作流。",
      usageLabel: "5h 剩余 11% · 7d 剩余 2%",
      usagePercent: 98,
      trackingMode: "window",
      resetAt: "2026-03-23 19:15:45",
      expiryAt: "2026-04-16 16:51:07",
      costLabel: "约 ¥6.6 / 坑位",
      sourceLabel: "Codex 本地会话日志",
      liveUsage: {
        provider: "OpenAI",
        accountEmail: "sunriseforever747@outlook.com",
        plan: "ChatGPT Team",
        subscriptionActiveUntil: "2026/04/16 16:51:07",
        fiveHour: {
          usedPercent: 89,
          remainingPercent: 11,
          resetsAt: "2026/03/18 16:32:14"
        },
        sevenDay: {
          usedPercent: 98,
          remainingPercent: 2,
          resetsAt: "2026/03/23 19:15:45"
        },
        totalTokens: 0,
        lastTokens: 0,
        sourceLabel: "Codex 本地会话日志",
        syncedAt: "2026/03/18 11:47:56"
      },
      notes: [
        "OpenAI 主线里当前最舒服的主力位。",
        "如果后续 Team 坑位持续便宜，直接继续补 OpenAI 流量池。",
      ],
    },
    {
      id: "openai-primary-b",
      provider: "OpenAI",
      accountLabel: "Codex 主力 B",
      email: "gabrielwas29nk@hotmail.com",
      plan: "ChatGPT Team",
      cluster: "openai",
      status: "paused",
      priority: 2,
      isActive: false,
      workspace: "xsfwnwgeq",
      statusDetail: "本周窗口已用尽，暂停使用，等待 2026-03-22 恢复。",
      usageLabel: "5h 剩余 100% · 7d 剩余 0%",
      usagePercent: 100,
      trackingMode: "window",
      resetAt: "2026-03-22",
      expiryAt: "2026-04-14",
      costLabel: "约 ¥6.6 / 坑位",
      sourceLabel: "用户手动确认 + 当前状态",
      liveUsage: {
        provider: "OpenAI",
        accountEmail: "gabrielwas29nk@hotmail.com",
        plan: "ChatGPT Team",
        fiveHour: {
          usedPercent: 0,
          remainingPercent: 100,
          resetsAt: "2026-03-22",
        },
        sevenDay: {
          usedPercent: 100,
          remainingPercent: 0,
          resetsAt: "2026-03-22",
        },
        sourceLabel: "用户手动确认",
        syncedAt: "2026-03-17 00:00",
      },
      notes: [
        "当前是独立邮箱下唯一 Team，可安全按邮箱自动对齐。",
        "目前周窗已用尽，等 3 月 22 日恢复后再重新接力。",
      ],
    },
    {
      id: "openai-primary-e",
      provider: "OpenAI",
      accountLabel: "Vucovs",
      email: "gabrielwas29nk@hotmail.com",
      plan: "ChatGPT Team",
      cluster: "openai",
      status: "ready",
      priority: 3,
      isActive: false,
      workspace: "Vucovs",
      statusDetail: "同一 ga 邮箱下新增的手动发货 Team，已记录订阅有效期，等待首次窗口同步。",
      usageLabel: "等待首次同步",
      usagePercent: 0,
      trackingMode: "window",
      expiryAt: "2026-04-19 12:57:38",
      costLabel: "手动发货 Team",
      sourceLabel: "手动录入 + Codex 登录态",
      liveUsage: {
        provider: "OpenAI",
        accountEmail: "gabrielwas29nk@hotmail.com",
        plan: "ChatGPT Team",
        subscriptionActiveUntil: "2026/04/19 12:57:38",
        fiveHour: {},
        sevenDay: {},
        sourceLabel: "Codex 登录态",
        syncedAt: "2026/03/19 19:37:00",
      },
      notes: [
        "2026-03-19 19:37 左右加入。",
        "手动发货，无平台网站。",
        "工作空间名：Vucovs。",
      ],
    },
    {
      id: "openai-primary-c",
      provider: "OpenAI",
      accountLabel: "LeaYundtiio",
      email: "sunriseforever747@outlook.com",
      plan: "ChatGPT Team",
      cluster: "openai",
      status: "paused",
      priority: 3,
      isActive: false,
      workspace: "LeaYundtiio",
      statusDetail: "上一轮已经在这个 Team 上把周窗打空了，当前暂停，等待 2026-03-23 19:15 恢复。",
      usageLabel: "5h 剩余 100% · 7d 剩余 0%",
      usagePercent: 100,
      trackingMode: "window",
      resetAt: "2026-03-23 19:15:00",
      expiryAt: "2026-04-16 12:30:28",
      costLabel: "约 ¥6.6 / 坑位",
      sourceLabel: "用户手动确认 + 当前状态",
      liveUsage: {
        provider: "OpenAI",
        accountEmail: "sunriseforever747@outlook.com",
        plan: "ChatGPT Team",
        subscriptionActiveUntil: "2026/04/16 12:30:28",
        fiveHour: {
          usedPercent: 0,
          remainingPercent: 100
        },
        sevenDay: {
          usedPercent: 100,
          remainingPercent: 0,
          resetsAt: "2026/03/23 19:15:00"
        },
        sourceLabel: "用户手动确认",
        syncedAt: "2026/03/18 16:25:00"
      },
      notes: [
        "团队 ID a7aec85c-4302-40e7-b684-3894ec648b65。",
        "和 RobertGreene7794（商家标记：zz304）一样挂在同一个 OpenAI 账号下。",
        "质保到 2026-03-31 19:07:59。",
      ],
    },
    {
      id: "openai-primary-d",
      provider: "OpenAI",
      accountLabel: "citel",
      email: "sunriseforever747@outlook.com",
      plan: "ChatGPT Team",
      cluster: "openai",
      status: "ready",
      priority: 4,
      isActive: false,
      workspace: "citel",
      statusDetail: "同一微软主号下新增的手动发货 Team，池子更小、人更少，适合继续做主线扩池。",
      usageLabel: "新补坑位，先作为接力与观察位",
      usagePercent: 6,
      trackingMode: "estimate",
      expiryAt: "2026-04-16",
      costLabel: "约 ¥6.6 / 坑位",
      sourceLabel: "手动录入订阅信息",
      notes: [
        "2026-03-16 左右新增。",
        "按一个月订阅估算到期约 2026-04-16。",
        "30 天质保，无管理页面。",
        "非批量邀请池，量少、手动发货、池子相对更小人更少。",
      ],
    },
    {
      id: "openai-old-fallback",
      provider: "OpenAI",
      accountLabel: "Codex Plus",
      email: "xnlyiyecue23495@outlook.com",
      plan: "ChatGPT Plus",
      cluster: "openai",
      status: "paused",
      priority: 5,
      isActive: false,
      statusDetail: "本周窗口已用尽，暂停使用，等待 2026-03-19 恢复。",
      usageLabel: "5h 剩余 100% · 7d 剩余 0%",
      usagePercent: 100,
      trackingMode: "window",
      resetAt: "2026-03-19",
      expiryAt: "2026-03-22",
      costLabel: "旧坑位，适合兜底",
      sourceLabel: "用户手动确认 + 当前状态",
      liveUsage: {
        provider: "OpenAI",
        accountEmail: "xnlyiyecue23495@outlook.com",
        plan: "ChatGPT Plus",
        fiveHour: {
          usedPercent: 0,
          remainingPercent: 100,
          resetsAt: "2026-03-19",
        },
        sevenDay: {
          usedPercent: 100,
          remainingPercent: 0,
          resetsAt: "2026-03-19",
        },
        sourceLabel: "用户手动确认",
        syncedAt: "2026-03-17 00:00",
      },
      notes: [
        "当前也是独立邮箱下唯一 Team，可安全按邮箱自动对齐。",
        "恢复后仍可作为兜底，不必急着丢。",
      ],
    },
    {
      id: "claude-pro-1",
      provider: "Claude",
      accountLabel: "Claude Pro 1",
      email: "el614493@gmail.com",
      plan: "Claude Pro",
      cluster: "observer",
      status: "expired",
      priority: 10,
      isActive: false,
      statusDetail: "截至 2026-03-16 已到期，暂不作为主线续费对象。",
      usageLabel: "当前不建议继续投入",
      usagePercent: 100,
      trackingMode: "window",
      expiryAt: "2026-03-16",
      costLabel: "历史月付",
      sourceLabel: "订阅到期信息",
      notes: [
        "如果后续 Anthropic 新一代明显反超，再考虑回归。",
      ],
    },
    {
      id: "claude-pro-2",
      provider: "Claude",
      accountLabel: "Claude Pro 2",
      email: "sunriseforever747@outlook.com",
      plan: "Claude Pro Gift 6m",
      cluster: "observer",
      status: "observe",
      priority: 11,
      isActive: false,
      statusDetail: "低频观察位，目前主要用来监控是否值得回到 Claude 主线。",
      usageLabel: "近阶段使用频率偏低",
      usagePercent: 5,
      trackingMode: "window",
      expiryAt: "2026-09-03",
      costLabel: "约 ¥440 / 6 个月",
      sourceLabel: "手动观测",
      notes: [
        "目前的主观体感仍不如 Codex 主线划算。",
      ],
    },
    {
      id: "claude-pro-3",
      provider: "Claude",
      accountLabel: "Claude Pro 3",
      email: "sunrisever52747@outlook.com",
      plan: "Claude Pro Gift 6m",
      cluster: "observer",
      status: "observe",
      priority: 12,
      isActive: false,
      statusDetail: "保留兜底与版本观察，不主动消耗。",
      usageLabel: "当前主要当观察样本",
      usagePercent: 3,
      trackingMode: "window",
      expiryAt: "2026-09-04",
      costLabel: "约 ¥440 / 6 个月",
      sourceLabel: "手动观测",
      notes: [
        "和 Pro 2 一样，先等下一代模型再决定是否回主线。",
      ],
    },
    {
      id: "kimi-coding",
      provider: "Kimi",
      accountLabel: "Kimi Allegretto",
      email: "Kimi Coding Plan",
      plan: "Allegretto 编程套餐",
      cluster: "api",
      status: "observe",
      priority: 20,
      isActive: false,
      statusDetail: "历史上为 OpenClaw API 接入而买，现在必要性明显下降。",
      usageLabel: "低频保留，观察是否续费",
      usagePercent: 8,
      trackingMode: "exact",
      costLabel: "¥199 / 月",
      tokensUsed: 1280000,
      tokensRemaining: 148720000,
      sourceLabel: "后续接 Kimi 控制台 / API",
      notes: [
        "只要 GPT Team 坑位继续便宜，Kimi 的性价比就难回到主线。",
      ],
    },
    {
      id: "qwen-dashscope",
      provider: "Qwen",
      accountLabel: "DashScope / Qwen",
      email: "阿里云百炼默认业务空间",
      plan: "按量 + 免费额度",
      cluster: "api",
      status: "ready",
      priority: 30,
      isActive: false,
      statusDetail: "后续接 DashScope 控制台 / API，用来观察 Qwen 相关额度和可用性。",
      usageLabel: "当前先保留精确额度入口",
      usagePercent: 0,
      trackingMode: "exact",
      costLabel: "优先消耗免费额度",
      tokensUsed: 0,
      tokensRemaining: 1000000,
      expiryAt: "2026-04-21",
      sourceLabel: "待接 DashScope 控制台 / API",
      notes: [
        "当前已知有 text-embedding-v4 免费额度。",
        "后续如果接 Qwen 主模型，再把模型级用量也并进来。",
      ],
    },
    {
      id: "gemini-advanced",
      provider: "Gemini",
      accountLabel: "Gemini Advanced",
      email: "gabrielwas29nk@gmail.com",
      plan: "学生教育会员",
      cluster: "observer",
      status: "observe",
      priority: 30,
      isActive: false,
      statusDetail: "低频保留，多模态和轻问答备用，不承担主力编码或推理。",
      usageLabel: "使用频率很低",
      usagePercent: 4,
      trackingMode: "estimate",
      expiryAt: "2026-11",
      costLabel: "学生权益",
      sourceLabel: "静态观察位，不做实时抓取",
      notes: [
        "前端演示类体验未达到预期，实际主线价值有限。",
      ],
    },
    {
      id: "zhipu-ocr",
      provider: "ZhipuAI",
      accountLabel: "GLM-OCR 包",
      email: "GLM OCR Resource Pack",
      plan: "3.5 亿 token 包",
      cluster: "api",
      status: "ready",
      priority: 40,
      isActive: false,
      statusDetail: "这是精确额度型资源，适合直接盯剩余额度和到期。",
      usageLabel: "额度充足，可继续 OCR",
      usagePercent: 9,
      trackingMode: "exact",
      expiryAt: "2026-06-08",
      costLabel: "已购入 ¥50.9",
      tokensUsed: 32000000,
      tokensRemaining: 318000000,
      sourceLabel: "Zhipu 控制台",
      notes: [
        "OCR 流量包和订阅型账号要分开看，别混成一个池。",
      ],
    },
  ],
  activityLog: [
    {
      id: "seed-1",
      at: "2026-03-16 18:30",
      kind: "note",
      title: "初始化策略样例",
      detail: "默认先用 OpenAI 主线账号，其他 provider 退到观察位。",
    },
  ],
  timelineLog: [],
};

export function cloneSeed(): DashboardState {
  return JSON.parse(JSON.stringify(dashboardSeed)) as DashboardState;
}
